const works = [
  {
    name: 'Multi-Post Stories',
    description: "A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a standard dummy text.",
    featuredImage: './assets/images/featured-placeholder.png',
    technologies: ['css', 'html', 'bootstrap', 'Ruby'],
    urlLive: '',
    urlRepo: '',
  },
  {
    name: 'Professional Art Printing Data More',
    description: "A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry's standard",
    featuredImage: './assets/images/modal-work-thumbnail.png',
    technologies: ['html', 'bootstrap', 'Ruby'],
    urlLive: '',
    urlRepo: '',
  },
  {
    name: 'Data Dashboard Healthcare',
    description: "A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry's standard",
    featuredImage: './assets/images/modal-work-thumbnail.png',
    technologies: ['html', 'bootstrap', 'Ruby'],
    urlLive: '',
    urlRepo: '',
  },
  {
    name: 'Website Portfolio',
    description: "A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry's standard",
    featuredImage: './assets/images/modal-work-thumbnail.png',
    technologies: ['html', 'bootstrap', 'Ruby'],
    urlLive: '',
    urlRepo: '',
  },
  {
    name: 'Professional Art Printing Data More',
    description: "A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry's standard",
    featuredImage: './assets/images/modal-work-thumbnail.png',
    technologies: ['html', 'bootstrap', 'Ruby'],
    urlLive: '',
    urlRepo: '',
  },
  {
    name: 'Data Dashboard Healthcare',
    description: "A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry's standard",
    featuredImage: './assets/images/modal-work-thumbnail.png',
    technologies: ['html', 'bootstrap', 'Ruby'],
    urlLive: '',
    urlRepo: '',
  },
  {
    name: 'Website Portfolio',
    description: "A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry's standard",
    featuredImage: './assets/images/modal-work-thumbnail.png',
    technologies: ['html', 'bootstrap', 'Ruby'],
    urlLive: '',
    urlRepo: '',
  },
];

export default works;